### PR TITLE
Try to install and update pip dependencies +

### PR DESCRIPTION
**Pull request by tbertels**
Try to install and update pip dependencies
More explicit messages
import_name -> importName (consistency)

### CODE REVIEW

**Comment by sqall01** [comment]
Hi,

can you change `importName` to `import_name`? The PEP specifications says variable names should not be in the camel-case format. I know, there are inconsistencies in the code. This is because I started the project using camel-case by not regarding the PEP specifications and during my refactoring to python3 I started changing things to PEP specifications. But since I did not touch every line, there are inconsistencies (which I hope will disappear over time).

**Comment by sqall01** [comment]
[clabot:check]

**Comment by sqall01** [comment]
Sorry to bother you before I work on your contribution. But before I can start, I have to ask you to accept the "Contributor License Agreement" of this project (available at https://gist.github.com/sqall01/b9460c19690d6a7397a9040142122cb4). Just respond with ***I have read the CLA Document and I hereby sign the CLA*** to accept it.

I just set something up to automate this process. Hopefully it works for the next contributor. But you are my first contributor that adds code :), so we have to do it manually now :)

**Comment by tbertels** [comment]
What does it add compared to the AGPL-3.0 license ?

**Comment by sqall01** [comment]
The AGPL-3.0 license is not changed with it. It only allows me to maintain the right to dual license the project (see here on the [README.md](https://github.com/sqall01/alertR#licensing-and-commercial-use)). Not that someone has ever asked for something like that or that I earned any money with it, but I worked for 6 years on the project now and do not want to give away the possibility.

**Comment by sqall01** [comment]
It seems you are not interested in giving me the permissions to use your code. That is unfortunate, since I cannot merge it then :(

**Pull request closed without merging**
